### ISSUE TITLE
Between game time does not follow parameters

### ISSUE THREAD

**Issue by e-straily** [AtlantisSports/uwh-refbox-rs#87]
**Describe the bug**
The Actual Time Between Games is not accurately reflecting the values given when choosing time parameters.

**To Reproduce**
It doesn't seem to work correctly at all, so I don't think there is anything specific to do to reproduce the issue. But editing the game's time parameters definitely causes the issue.

**Expected behavior**
The Nominal Time Between Games parameter should set the time between games if there are no time interruptions or edits during the prior game. If there is a time interruption (pressing the time, ref timeout, team timeout, penalty shot), or time edit, then the Actual Time Between Games will be adjusted up or down equal to the sum of the interruptions and any time edits, unless the value reaches the Minimum Time Between Games floor. 

If the sum of interruptions and time edits causes the game to end sooner than the parameters intended, then the Actual Time Between games will become larger than the Nominal Time Between Games. 

If the sum of interruptions and time edits causes the game to end later than the parameters intended, then the Actual Time Between games will become smaller than the Nominal Time Between Games down until the value equals the Minimum Time Between Games.

**Comment by TristanDebrunner** [comment]
Could you give an actual description of what is wrong? By my testing, the expected behavior you described is what actually happens.

**Comment by e-straily** [comment]
I think the issue may have been because it was a cumulative process. We didn't restart the program after choosing a new time and so the program kept the original time and then adjusted the next start time with the previous settings in mind. It may be good to some way clear the prior settings and work from a clean slate. 

Example: Game is running at a certain parameter set, organizers want to start a new parameter set, they change the parameters and manually adjust the time until next game to meet their new desired start time (this time could be before or after the calculated start of the next game from the original parameter set) and from then on out only the new parameters matter.

**Comment by TristanDebrunner** [comment]
There is one issue here that I've found: When the settings are changed, the tracking of how far behind/ahead we are overall does not get reset. So if it thinks we are 10 minutes behind when the settings are changed, the next end of game will still apply those 10 minutes to its calculated time between games. The tracking should be reset such that when the timing rules are changed, the next start time is considered to be the correct start time, and subsequent games will start correctly based on that.

Otherwise, I have not found any issues. The new timing rules appear to apply as soon as they are entered. @e-straily does this sound correct to you, or do you think there are other additional bugs?

**Comment by e-straily** [comment]
Yes that does sound correct for the issue I found and your suggestion for the reset sounds like what I was thinking too.
